web: python manage.py migrate --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2
worker: celery -A backend worker --loglevel=info --concurrency=2
beat: celery -A backend beat --loglevel=info
