# Generated by Django 4.2.7 on 2026-09-18 13:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_course_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('pass_mark', models.PositiveIntegerField(default=50, help_text='Percentage of max_score required to be marked competent', validators=[django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('allow_resubmission', models.BooleanField(default=True)),
                ('allowed_file_types', models.CharField(default='pdf,zip,ipynb,py,js,ts,csv,docx,md,txt', help_text='Comma-separated extensions; blank allows any', max_length=255)),
                ('max_file_size_mb', models.PositiveIntegerField(default=25)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('pass_mark', models.PositiveIntegerField(default=70, help_text='Percentage required to be marked competent', validators=[django.core.validators.MaxValueValidator(100)])),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 = no limit')),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.lesson')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single correct answer'), ('multiple', 'Multiple correct answers'), ('true_false', 'True or false')], default='single', max_length=20)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, default='', help_text='Shown after the attempt is graded')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.quizquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('competent', 'Competent'), ('not_yet_competent', 'Not Yet Competent')], default='pending', max_length=20)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.enrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.quiz')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['enrollment', 'quiz'], name='core_quizat_enrollm_ce303e_idx')],
                'unique_together': {('quiz', 'enrollment', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/%Y/%m/')),
                ('text_answer', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded')], default='submitted', max_length=20)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('competent', 'Competent'), ('not_yet_competent', 'Not Yet Competent')], default='pending', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='core.enrollment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['enrollment', 'assignment'], name='core_assign_enrollm_6e8e81_idx'), models.Index(fields=['assignment', 'status'], name='core_assign_assignm_09a883_idx')],
                'unique_together': {('assignment', 'enrollment', 'attempt_number')},
            },
        ),
    ]
