# Generated by Django 4.2.7 on 2026-09-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assessments'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a top-level category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category'),
        ),
    ]
